name: Deploy mern to eks

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Login to ECR
        run:  |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 889168908024.dkr.ecr.ap-south-1.amazonaws.com

      - name: Delete old images
        run: |
          docker rmi -f $(docker images -q)
          aws ecr batch-delete-image --repository-name artify_backend  --region ap-south-1 --image-ids “$(aws ecr list-images --repository-name artify_backend --query 'imageIds[*]' --output json)”
          aws ecr batch-delete-image --repository-name artify_frontend  --region ap-south-1 --image-ids “$(aws ecr list-images --repository-name artify_frontend --query 'imageIds[*]' --output json)”

      - name: Build Backend Image
        run: |
          docker build --no-cache -t artify_backend:latest ./backend
          docker tag artify_backend:latest 889168908024.dkr.ecr.ap-south-1.amazonaws.com/artify_backend:latest
          docker push 889168908024.dkr.ecr.ap-south-1.amazonaws.com/artify_backend:latest

      - name: Build Frontend Image
        run: |
          docker build --no-cache -t artify_frontend:latest ./frontend
          docker tag artify_frontend:latest 889168908024.dkr.ecr.ap-south-1.amazonaws.com/artify_frontend:latest
          docker push 889168908024.dkr.ecr.ap-south-1.amazonaws.com/artify_frontend:latest

      - name: Show docker images
        run: |
          docker images

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name clusterartify
          
      - name: Deploy to Kubernetes 
        run: |
          kubectl apply -f backend/backend-deployment.yaml
          kubectl apply -f backend/backend-service.yaml
          kubectl apply -f frontend/frontend-deployment.yaml
          kubectl apply -f frontend/frontend-service.yaml
          
      - name:  Restart Deployments
        run:  |
          kubectl rollout restart deployment backend-deployment
          kubectl rollout restart deployment frontend-deployment
